### ISSUE TITLE
Suggestion - use width of the page 

### ISSUE THREAD

**Issue by Lesley2** [Acfee/ehna-dev#10]
So I know you going to hate me, but can we spread out v4 a bit to use more of the grey space and utilise the width of the page- its just feeling a little squashed and boxy.

**Comment by getwes** [comment]
I was wondering how long it would take for this question to come up. 

-- Idea behind v4 --
The idea was to provide a clean simplistic interface with easy navigation and contained content to provide a easy on the eye experience. 

Currently v3 uses almost-full page width. 
I was hoping to use a smaller container size for v4.

Some suggestions would be good @Lesley2 @SBroomhead ??

**Comment by SBroomhead** [comment]
I asked the same a while back and Wes felt strongly about the slimmer look. So, I'd like to leave this issue until all functionality is in place and then revisit it. If there's enough going on, we might find the streamlined look works. I'm not sure yet.

**Comment by SBroomhead** [comment]
As an example, have a look at the Initiatives list at http://ehna.static-a.net/initiatives When I pen these pages, I'm not sure what the most important thing to look at is, because it all looks quite similar. That's part of why I thought the middle panel should be wider ,so that for any page, the main content is obvious.

**Comment by getwes** [comment]
Im happy to use the v3 style page with of 
> 1170px
instead of 
> 1070

I will make changes immediately so you get a feel for the broadened layout.

**Comment by getwes** [comment]
Page has been updated to full width as **suggested**
