### ISSUE TITLE
Bug - text extending the text border 

### ISSUE THREAD

**Issue by Lesley2** [Acfee/ehna-dev#11]
MTN under organisations text is stretching beyond the text box and into the grey space 
![snip20170309_100](https://cloud.githubusercontent.com/assets/26297259/23748219/f434d5ce-04c2-11e7-94e5-36fae31c953f.png)

**Comment by getwes** [comment]
@Lesley2 Adjusting the container size to take up the full page has sorted the issue out.

**Comment by Lesley2** [comment]
Hey @getwes - so the MTN text is still extending the border of the text box. Its better, but the spacing is also different 
![snip20170310_107](https://cloud.githubusercontent.com/assets/26297259/23792036/a21c2742-0585-11e7-9a9c-808194f0335c.png)

**Comment by getwes** [comment]
![screen shot 2017-03-10 at 12 39 21 pm](https://cloud.githubusercontent.com/assets/24999420/23792190/9ba67f76-058e-11e7-9779-317a9b52c609.png)

This is what i see. @Lesley2

**Comment by SBroomhead** [comment]
@getwes I see what @Lesley2 sees, as per below: 
![screenshot 2017-03-11 17 21 12](https://cloud.githubusercontent.com/assets/23177483/23824431/5e53db9a-067f-11e7-9341-fe827224f942.png)

**Comment by getwes** [comment]
@SBroomhead @Lesley2 If you look at my screenshot the MTN Text says "MTN says data is..." and if you look at your screenshots supplied. it says "it will extends to..." that is definitely cache issue. please will you find a way to clear your cache for eHNA website and try again.

**Comment by SBroomhead** [comment]
@getwes I've re-opened this since I still see it. I'll attach some screenshots.

**Comment by SBroomhead** [comment]
![screenshot 2017-03-31 14 54 20](https://cloud.githubusercontent.com/assets/23177483/24551292/386a04e2-1622-11e7-884e-1eb16b966eb1.png)
![screenshot 2017-03-31 14 54 09](https://cloud.githubusercontent.com/assets/23177483/24551293/386d4382-1622-11e7-8a12-80f5a9cf9217.png)
![screenshot 2017-03-31 14 53 50](https://cloud.githubusercontent.com/assets/23177483/24551294/3871a256-1622-11e7-88ad-857c0dfcb9cc.png)
![screenshot 2017-03-31 14 53 43](https://cloud.githubusercontent.com/assets/23177483/24551295/38730880-1622-11e7-8273-9927e495b550.png)
![screenshot 2017-03-31 14 53 35](https://cloud.githubusercontent.com/assets/23177483/24551296/38789c78-1622-11e7-8d17-c00e60d8eda4.png)
