### ISSUE TITLE
enhancement - missing editors on the home page

### ISSUE THREAD

**Issue by Lesley2** [Acfee/ehna-dev#12]
The editors section in the left hand column is missing in v4

**Comment by getwes** [comment]
@Lesley2 @SBroomhead this piece has taken up the editor space in v4. 

![screen shot 2017-03-10 at 11 51 22 am](https://cloud.githubusercontent.com/assets/24999420/23790496/f4d971a4-0587-11e7-8122-cdfb08a80cb2.png)

What do you guys suggest?

**Comment by SBroomhead** [comment]
@getwes having the editors there gives credibility. A lot of people have commented on it. Let's add them to below the Acfee piece you added please.

**Comment by getwes** [comment]
@SBroomhead will put the editors back under the Acfee piece.

**Comment by getwes** [comment]
@SBroomhead @Lesley2 Editors have been added back in the left hand sidebar of v4
