### ISSUE TITLE
enhancement - bullets from v3 differ from v4 

### ISSUE THREAD

**Issue by Lesley2** [Acfee/ehna-dev#13]
So the bullets in v4 are great, and is a big improvement from v3, but the bullets pulling from v3 onto v4 aren't quite right. So v4 is adding numbers where v3 had two different bullets making it confusing. If we now have the option for bullets to be numbers aswell thats great (not a v3 option) - but numbers and different bullets obviously mean different things at different times (sorry not a great explanation, please see screenshots below) Screen shot 1 and 3 are v4, and screenshot 2 and 4 are v3

![snip20170310_103](https://cloud.githubusercontent.com/assets/26297259/23791774/a401bf46-0584-11e7-8753-21e27dd2458d.png)
![snip20170310_104](https://cloud.githubusercontent.com/assets/26297259/23791783/abb761c8-0584-11e7-9594-f688e8e58b7b.png)
![snip20170310_105](https://cloud.githubusercontent.com/assets/26297259/23791799/b24d06d2-0584-11e7-9254-0e96293110fc.png)
![snip20170310_106](https://cloud.githubusercontent.com/assets/26297259/23791800/b8400436-0584-11e7-9301-a59ed0ee63ce.png)

**Comment by getwes** [comment]
@Lesley2 Thanks Les. i didnt even notice. this is just a bug. nothing major.
