### ISSUE TITLE
Question - v3 left and right panels remains the same for all views 

### ISSUE THREAD

**Issue by Lesley2** [Acfee/ehna-dev#14]
Just a quick observation rather than question - In v3 the left and right panels stay constant for all views, including people, orgs, initiatives etc. In v4, it doesn't. The left panel is the same but the right panel just shows related initiatives and the sponsored by box (which I think we decided to remove as we also have ehna is an initiative of Acfee in the left panel)

**Comment by getwes** [comment]
@Lesley2 @SBroomhead Just to clear up some confusion. the "Sponsored" text in the "Right Sidebar" should actually be named "Adverts" -- for some reason i used sponsored.

**Comment by getwes** [comment]
@Lesley2 @SBroomhead The right hand panel changes depending if the content piece busy being viewed has related content examples below:

> - Articles
> - Right Sidebar > Will have related articles. ( if there are any )

> - People
> - Right Sidebar > Will have that person's articles ( if there are any )

> - Initiatives
> - Right Sidebar > Will have related organisations ( if it is an organisation initiative )

> - Organisations
> - Right Sidebar > Will have organisation related initiatives and organisation people ( if it has any )

> - Countries 
> - Right Sidebar > Will have initiatives that are related that that country ( if it has any )

@Lesley2  hope this clears up the confusion.

**Comment by Lesley2** [comment]
ahh ok cool - having a look now. Looks good. this is very minor, but the acfee logo for related articles gets cut off - anyway we can enlarge the box slightly so it fits or make it smaller so it fits. The entire box doesn't have to be bigger, just the image box to fill that space maybe? 
![snip20170310_108](https://cloud.githubusercontent.com/assets/26297259/23792703/69dac17e-0588-11e7-90ba-fe765d8190ac.png)

**Comment by getwes** [comment]
@Lesley2 im using an actual style for the image that uses the 

> backgrouns-size: cover

Which gives it that look. What i can do is use this instead

> backgrouns-size: **contain**

which will sort it out

**Comment by SBroomhead** [comment]
@getwes @Lesley2 I really like the dynamic right panel. It's the kind of connected information that I think users will like too
