### ISSUE TITLE
Suggestion : People, Initiative, Org profile - enlarge person image and people images at the back  

### ISSUE THREAD

**Issue by Lesley2** [Acfee/ehna-dev#15]
A suggestion - The people, initiative org and country profiles, currently have a lot of white wasted space. Anyway we can enlarge the main image slightly as well as the images in the background?  Also just a second point - some people have eHealth News Africa below there name like the image provided. Which makes it appear as though they work for ehna or is affiliated with ehna. I understand its simply a home button but can we remove that? 
![snip20170310_110](https://cloud.githubusercontent.com/assets/26297259/23793149/3142efa6-058a-11e7-9efc-7e076e308e0a.png)
![snip20170310_109](https://cloud.githubusercontent.com/assets/26297259/23793159/369a2a64-058a-11e7-805a-43b46bb21600.png)

**Comment by SBroomhead** [comment]
@Lesley2 your comments seem right

**Comment by getwes** [comment]
@Lesley2 @SBroomhead cool. i will adjust to above suggested comments
