### ISSUE TITLE
Bug - article text on home page doesn't show the first line of the article but the last line 

### ISSUE THREAD

**Issue by Lesley2** [Acfee/ehna-dev#16]
A couple of articles I've come across are displaying the last lines of the articles on the home page instead of the first line. One is also showing no text on the home page. 

![snip20170313_117](https://cloud.githubusercontent.com/assets/26297259/23861236/baa6b3d2-0809-11e7-83dc-d92a89f9763f.png)
![snip20170313_116](https://cloud.githubusercontent.com/assets/26297259/23861245/c0ba8f96-0809-11e7-8dd9-50a44dbd26b0.png)
![snip20170313_115](https://cloud.githubusercontent.com/assets/26297259/23861252/c87cfe58-0809-11e7-8fd2-2d7e874262c0.png)
![snip20170313_114](https://cloud.githubusercontent.com/assets/26297259/23861266/d085b5cc-0809-11e7-8e8b-f6d4de930820.png)

**Comment by getwes** [comment]
Issue fixed.
