### ISSUE TITLE
suggestion - ehna logo to include © 2017  About  Terms  Help

### ISSUE THREAD

**Issue by Lesley2** [Acfee/ehna-dev#18]
the ehna logo on v3 incorporates "© 2017  About  Terms  Help" icons, where in v 4 they in a separate box. Can I suggest we use the same format as v3 - that makes it one less box in the left panel and frees up extra space for the ehna is an initiative of acfee box that we want to add together with the editors box.

**Comment by getwes** [comment]
@Lesley2 @SBroomhead 

I designed them to be seperate for the following reason:

<img width="284" alt="screen shot 2017-03-15 at 6 28 33 am" src="https://cloud.githubusercontent.com/assets/24999420/23933659/abb8c1a4-0948-11e7-9d65-90e4a70c856c.png">

When a user signs in. eHNA gets personalised to show my details. A kind of sense that eHNA is mine, this is my dashboard and my section of eHNA.

**Comment by SBroomhead** [comment]
@getwes I like your v4 approach for this
