### ISSUE TITLE
Bug: Author links don't work

### ISSUE THREAD

**Issue by Lesley2** [Acfee/ehna-dev#2]
The author links don't work

**Comment by getwes** [comment]
Ok will check on that @Lesley2

**Comment by getwes** [comment]
Ok so once we get to a point where the issue gets resolved. and you have confirmed it. We can close the issue

**Comment by getwes** [comment]
Issues can alwasys be re-opened again.

**Comment by getwes** [comment]
To notify people in this conversion you can type their username with the @ sign before. so for example i need this comment to notify @Lesley2 @SBroomhead

**Comment by getwes** [comment]
That should be it for the tutorial. i hope this helps. To find "closed" issues. following this like: https://github.com/Acfee/ehna-dev/issues?q=is%3Aissue+is%3Aclosed or clicking "closed" in the issues list will bring you to all closed issues.

**Comment by Lesley2** [comment]
ok great - thanks Wes. think I can handle adding a new issue @getwes
