### ISSUE TITLE
Bug: text disappears when you add your profile image 

### ISSUE THREAD

**Issue by Lesley2** [Acfee/ehna-dev#22]
I added my name etc when logging in and then went to add my profile image. Once added, the text that I had previously added disappeared. Also the profile image looks a bit squashed.

**Comment by getwes** [comment]
Hi @Lesley2 || Im also going to notifiy @SBroomhead for this discussion. 

Basically how it works is "General Settings" and "Change Photo" are separate uploads. 

So for example. if i change my name and immediately change my photo without saving my general settings first. my updated text wont be there. its like publishing on v3. if you alter the body of an article without saving it first and you upload a article photo. the text gets restored to default. 

So the ideal option as iv seen on many sites. including Github. is that the "General Settings" changes need to be saved first once you have editied them. using the "Update General" button.

**Comment by SBroomhead** [comment]
@getwes a lot of sites have this issue and it can be irritating for a user. We could solve it with code automatically persisting changes to the DB. If that's not possible, can we add a pop-up in between the two that says "Do you want to save the changes you've made so far?"
