### ISSUE TITLE
bug- affiliations 

### ISSUE THREAD

**Issue by Lesley2** [Acfee/ehna-dev#24]
The affiliations icon doesn't work. When you click it this happens 
![snip20170314_125](https://cloud.githubusercontent.com/assets/26297259/23892933/de0da41e-089c-11e7-8a6b-a1648ee0dcf9.png)

**Comment by getwes** [comment]
@Lesley2 yes this i am aware of. its pending dev. a couple of weeks ago @SBroomhead and myself had a phone call regarding this. there were a few things i was unsure of but everything was cleared up in that phone call. however pending the phone call i moved the dev along to progress in other areas. i will get back to this.
