### ISSUE TITLE
Suggestion - add tags to favourites 

### ISSUE THREAD

**Issue by Lesley2** [Acfee/ehna-dev#25]
A key aspect of favourites for me is to be able to have tags that you favourite or that you add to you list - so you will be able to access key issues you are interested in - e.g. - maternal and child health, or HIV/AIDS or TB. You can't currently add them to favourites - being able to navigate using tabs will be enormously helpful as you will be able to see what articles are available, initiatives, orgs are addressing those issues etc

**Comment by getwes** [comment]
Thanx @Lesley2. 

@SBroomhead this is a very interesting suggestion. being able to favorite tags in order to quickly get related content to a tag you find useful??

**Comment by SBroomhead** [comment]
@Lesley2 it's a great suggestion. I've been playing around with the site and realised that our Favourites functionality does quite a bit of what we planned to do with Lists. So I agree, let's go with supporting more Favourites options. Also @Lesley2 let's give the Lists a very careful review. It's a brand new idea, doesn't exist anywhere else in social-media-land so we need to make sure we're not on a wild goose chase. At the same time, it's possibly critical to how we want to handle support for Groups. Both @getwes and @Lesley2 please make sure you have reviewed both of the documents I've prepared for Vincent, in the same Dev shared folder, and shout if there is anything that we're not in sync on.

**Comment by getwes** [comment]
Users can now add tags to favorites
