### ISSUE TITLE
bug - editors 

### ISSUE THREAD

**Issue by Lesley2** [Acfee/ehna-dev#26]
This is how editors box currently looks on my side - all the images are missing 
![snip20170314_126](https://cloud.githubusercontent.com/assets/26297259/23894255/b1823bb2-08a1-11e7-99d6-64ca90efe737.png)

**Comment by getwes** [comment]
@Lesley2 Strange. this tile should change however to only include names as per @SBroomhead suggestion. as we need the "ehna is an initiative of acfee" - this is a pending issue waiting to get resolved.
