### ISSUE TITLE
Fix - Publishing article, bullets 

### ISSUE THREAD

**Issue by Lesley2** [Acfee/ehna-dev#28]
When you select the bullets in publishing it shows 2 bullets. 
![snip20170322_24](https://cloud.githubusercontent.com/assets/26297259/24191421/1a0190e8-0eec-11e7-9464-274207a5f243.png)

**Comment by Lesley2** [comment]
Also - can we add the number options for bullets. Tom had a list of 23 bullets in an article the other day and the option to rather show number would have been really helpful. Especially when referring to bullet 17 for example - instead of people having to count the bullets manually to have them be represented as numbers e.g. 1) 2) 3) etc or 1. 2. 3.

**Comment by getwes** [comment]
I have sorted out the problem with the two bullets from the screen shot.
