### ISSUE TITLE
enhancement - Initiative, Orgs, country views 

### ISSUE THREAD

**Issue by Lesley2** [Acfee/ehna-dev#38]
Just checking - the people views look different to initiatives, orgs and country views. Did we decide to standardise them to all look like the people views? 
![snip20170329_5](https://cloud.githubusercontent.com/assets/26297259/24460183/d07012f8-149d-11e7-833e-0b75c7efe351.png)
![snip20170329_6](https://cloud.githubusercontent.com/assets/26297259/24460196/dabd7d2c-149d-11e7-954e-13496b84ed16.png)

**Comment by getwes** [comment]
@Lesley2 This will be fixed by day end
