### ISSUE TITLE
Bug - country text being cut off 

### ISSUE THREAD

**Issue by Lesley2** [Acfee/ehna-dev#40]
Text for some of the countries are being cut off. 

![snip20170329_8](https://cloud.githubusercontent.com/assets/26297259/24460646/3508cd76-149f-11e7-962c-29da100b3cab.png)

**Comment by getwes** [comment]
@Lesley2 The tet is not being cut off. that is the end of a paragraph. the feed works in paragraphs and with Benin. the first paragraph ends with "initiatives". Although it looks like its cut off. its not.
