### ISSUE TITLE
bug - editors 

### ISSUE THREAD

**Issue by Lesley2** [Acfee/ehna-dev#41]
Hey wes - I've cleared my Cache - and the editors box still shows up empty my side. 

![snip20170329_9](https://cloud.githubusercontent.com/assets/26297259/24461274/e2fbf38a-14a0-11e7-925d-2f45551a43ae.png)

**Comment by getwes** [comment]
@Lesley2 This is what i see

<img width="290" alt="screen shot 2017-03-30 at 7 56 01 am" src="https://cloud.githubusercontent.com/assets/24999420/24489538/619d17e6-151e-11e7-8c5c-aa2dd0cf5c81.png">

Im not 100% sure what is happening your side
