### ISSUE TITLE
Publications not reflected on personal profile

### ISSUE THREAD

**Issue by SBroomhead** [Acfee/ehna-dev#47]
@getwes - adding a publication on the profile settings page works well, but it isn't shown anywhere on the profile view page. Can this be a subtab, perhaps to replace the Articles sub-tab, since Articles are shown in the right column?

**Comment by getwes** [comment]
@SBroomhead  i can make a dynamic switcher that if the user has NO publications the "articles" tab will show else the "publications" tab will show
