### ISSUE TITLE
Bug - the sponsored link doesn't work 

### ISSUE THREAD

**Issue by Lesley2** [Acfee/ehna-dev#8]
The link when you click on sponsored in the right hand column on acfee on the home page doesn't work. Also it has an image for the AeF report and not Acfee logo

**Comment by getwes** [comment]
Do we need the actual "Sponsored" heading in the right-sidebar to actually go anywhere?
@Lesley2  @SBroomhead

**Comment by Lesley2** [comment]
good questions @getwes - right now we have "ehna is an initiative of Acfee" in the left hand column and "sponsored" in the right hand column. we don't need both

**Comment by getwes** [comment]
No i agree @Lesley2 . we dont need both. @SBroomhead what do you suggest?

**Comment by SBroomhead** [comment]
Acfee is an initiative of eHNA is perfect on the left. The one on the right can be removed. But shall we add the small subtext and the image to the left? Also, if we use the subtext, Ousmane's asked that we say drop the word "international" and simply say "Acfee is a network ..."

**Comment by getwes** [comment]
> Ousmane's asked that we say drop the word "international" and simply say "Acfee is a network ..."
Im happy to make this change @SBroomhead
